### ISSUE TITLE
Add Header and Footer to page

### ISSUE THREAD

**Issue by dpalharini** [dimkanovikov/PagesTextEdit#2]
Hi, @dimkanovikov 

First of all, I like to congratulate you for the wonderful work you did in the PageTextEdit, that was a clean and well made solution. I was struggling for weeks to do something like that, until I found your solution.

I wondering if you have any ideas about how can I add a page header and footer into the PagesTextEdit?Something like the Word does? 

Thanks in advance.

**Comment by dimkanovikov** [comment]
Hi, @dpalharini

Thanks a lot!

You can implement drawing of headers and footers by extending PagesTextEdit class. Look at function PagesTextEdit::paintPageNumbers () it will be good start point for implementation.

What you need is detect page header or footer rect and draw it if they are visible on screen.

**Comment by yunushkin88** [comment]
Hi @dimkanovikov 
Page numbers in the PagesTextEdit project are displayed perfectly, which is cool, but when I try to print a document in the output file, I usually do it .pdf doesn't display page numbers, how can fix it?
