### ISSUE TITLE
QGraphicsView Page 。

### ISSUE THREAD

**Issue by ghost** [dimkanovikov/PagesTextEdit#3]
Hi,I have a question to ask you . How to implement a QGraphicsView drawing board that can scroll up and down?

**Comment by dimkanovikov** [comment]
Hey, look at this for interactive graphics view https://github.com/dmatetelki/qtmindmap

**Comment by ghost** [comment]
thank you very much!

**Comment by ghost** [comment]
I want to implement such a demand, a panel, the panel can scroll, when the brush into the second page and not at the end of the first, the first page of the line and line to connect the second page. And so on, just like the text editor you implement, you can automatically add pages.How do I implement it? I referred to your page - page text editor, but failed.Thans.

**Comment by dimkanovikov** [comment]
Not really understand what you mean... Maybe you can add a screenshot to demonstrate what you need and I can point you to a more related example.
